apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  index.html: |
    <h1>Hello Kubernetes Helm Tutorial</h1>
    <h2>Author: "<yournamehere>"</h2>
    <p>If you can see this page, that means the content has been mounted to the pod through this configmap correctly.<p>